// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xeno.Starstay.Data;

#nullable disable

namespace Xeno.Starstay.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430055745_AddBookingCancellationState")]
    partial class AddBookingCancellationState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Xeno.Starstay.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHost")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "starstay-seed-host-curator",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a4c140f0-1e42-4830-ac92-aa3c36d4f1d3",
                            DisplayName = "Starstay Curator",
                            Email = "curator@starstay.local",
                            EmailConfirmed = true,
                            IsHost = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CURATOR@STARSTAY.LOCAL",
                            NormalizedUserName = "CURATOR@STARSTAY.LOCAL",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e7da812-b0b3-4f01-b10e-582c415acaa1",
                            Species = "Zeta Reticulan",
                            TwoFactorEnabled = false,
                            UserName = "curator@starstay.local"
                        });
                });

            modelBuilder.Entity("Xeno.Starstay.Models.StarshipBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalNotes")
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<DateTime?>("CancelledUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CycleCount")
                        .HasColumnType("int");

                    b.Property<string>("GuestUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<int>("StarshipListingId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalNebulaCredits")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuestUserId");

                    b.HasIndex("StarshipListingId");

                    b.ToTable("StarshipBookings");
                });

            modelBuilder.Entity("Xeno.Starstay.Models.StarshipListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlienLocation")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<bool>("AllowsAlienPets")
                        .HasColumnType("bit");

                    b.Property<string>("AmenityNotes")
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<string>("AtmosphereProfile")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GravityProfile")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("HasBioluminescentSpa")
                        .HasColumnType("bit");

                    b.Property<bool>("HasOxygen")
                        .HasColumnType("bit");

                    b.Property<bool>("HasQuantumDock")
                        .HasColumnType("bit");

                    b.Property<string>("HostUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NightlyRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("SupportsSiliconLifeforms")
                        .HasColumnType("bit");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("HostUserId");

                    b.ToTable("StarshipListings");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            AlienLocation = "Orbit of Velora Prime",
                            AllowsAlienPets = true,
                            AmenityNotes = "Pet alcoves, dew-fed greenhouse bar, and dusk-cycle observation petals.",
                            AtmosphereProfile = "Oxygen-rich",
                            CreatedUtc = new DateTime(2026, 1, 5, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Earthlike pull",
                            HasBioluminescentSpa = true,
                            HasOxygen = true,
                            HasQuantumDock = false,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 428.00m,
                            PhotoUrl = "/images/seed-listings/velora-orchid-ring.png",
                            Summary = "A living garden suite suspended inside an orchid halo with breathable air and moonlit lounge petals.",
                            SupportsSiliconLifeforms = false,
                            VesselName = "The Velora Orchid Ring"
                        },
                        new
                        {
                            Id = 1002,
                            AlienLocation = "Shard Caverns of Khepri-9",
                            AllowsAlienPets = false,
                            AmenityNotes = "Mineral-safe surfaces, resonance sleeping pod, and fracture-light meditation gallery.",
                            AtmosphereProfile = "Variable blend filters",
                            CreatedUtc = new DateTime(2026, 1, 6, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Low-gravity drift",
                            HasBioluminescentSpa = false,
                            HasOxygen = false,
                            HasQuantumDock = false,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 512.00m,
                            PhotoUrl = "/images/seed-listings/prism-silica-vault.png",
                            Summary = "Crystal-carved luxury for mineral-based travelers who want reflective stillness and gemstone acoustics.",
                            SupportsSiliconLifeforms = true,
                            VesselName = "The Prism Silica Vault"
                        },
                        new
                        {
                            Id = 1003,
                            AlienLocation = "Methane Crown above Oort Lysithea",
                            AllowsAlienPets = false,
                            AmenityNotes = "Warp-lift docking perch, pressure-calibrated lounge, and thunderwatch observation wall.",
                            AtmosphereProfile = "Methane-friendly",
                            CreatedUtc = new DateTime(2026, 1, 7, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Earthlike pull",
                            HasBioluminescentSpa = false,
                            HasOxygen = false,
                            HasQuantumDock = true,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 389.00m,
                            PhotoUrl = "/images/seed-listings/amber-gaslight-pod.png",
                            Summary = "A pressurized refinery-lounge retreat bathed in amber haze and gas giant lightning beyond the glass.",
                            SupportsSiliconLifeforms = false,
                            VesselName = "The Amber Gaslight Pod"
                        },
                        new
                        {
                            Id = 1004,
                            AlienLocation = "Meridian Dock Nine",
                            AllowsAlienPets = false,
                            AmenityNotes = "Hover lounge, grav-tuned sleep deck, and concierge docking beacon access.",
                            AtmosphereProfile = "Oxygen-rich",
                            CreatedUtc = new DateTime(2026, 1, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Adjustable grav-field",
                            HasBioluminescentSpa = false,
                            HasOxygen = true,
                            HasQuantumDock = true,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 601.00m,
                            PhotoUrl = "/images/seed-listings/halo-drift-observatory.png",
                            Summary = "A floating observatory loft with adjustable gravity and front-row views of premium docking traffic.",
                            SupportsSiliconLifeforms = false,
                            VesselName = "The Halo Drift Observatory"
                        },
                        new
                        {
                            Id = 1005,
                            AlienLocation = "Moonpool Crescent of Naia V",
                            AllowsAlienPets = false,
                            AmenityNotes = "Glow-tide spa basin, shell resonance audio, and waterglass meditation corridor.",
                            AtmosphereProfile = "Oxygen-rich",
                            CreatedUtc = new DateTime(2026, 1, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Moonlight float",
                            HasBioluminescentSpa = true,
                            HasOxygen = true,
                            HasQuantumDock = false,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 544.00m,
                            PhotoUrl = "/images/seed-listings/biolume-tide-conservatory.png",
                            Summary = "A translucent marine biosuite with breathable sea-light, moonpool rituals, and luminous rest decks.",
                            SupportsSiliconLifeforms = false,
                            VesselName = "The Biolume Tide Conservatory"
                        },
                        new
                        {
                            Id = 1006,
                            AlienLocation = "Rift Forge of Volkris",
                            AllowsAlienPets = false,
                            AmenityNotes = "Magma-view parlor, basalt sleep dais, and ritual dining chamber carved into the forge wall.",
                            AtmosphereProfile = "Variable blend filters",
                            CreatedUtc = new DateTime(2026, 1, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Earthlike pull",
                            HasBioluminescentSpa = false,
                            HasOxygen = false,
                            HasQuantumDock = false,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 468.00m,
                            PhotoUrl = "/images/seed-listings/obsidian-ember-sanctum.png",
                            Summary = "An obsidian refuge carved into a volcanic chasm for travelers who like their luxury ceremonial and dark.",
                            SupportsSiliconLifeforms = true,
                            VesselName = "The Obsidian Ember Sanctum"
                        },
                        new
                        {
                            Id = 1007,
                            AlienLocation = "Cloudreef Belts of Aurel",
                            AllowsAlienPets = true,
                            AmenityNotes = "Aerial companion roosts, cloud deck tea rail, and featherweight hammock canopy.",
                            AtmosphereProfile = "Oxygen-rich",
                            CreatedUtc = new DateTime(2026, 1, 11, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Low-gravity drift",
                            HasBioluminescentSpa = false,
                            HasOxygen = true,
                            HasQuantumDock = false,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 497.00m,
                            PhotoUrl = "/images/seed-listings/aurelian-cloudreef-nest.png",
                            Summary = "A sky-lodge above luminous cloud reefs with floating gardens and pet-friendly perch zones.",
                            SupportsSiliconLifeforms = false,
                            VesselName = "The Aurelian Cloudreef Nest"
                        },
                        new
                        {
                            Id = 1008,
                            AlienLocation = "Crystal Dunes of Sereph-4",
                            AllowsAlienPets = false,
                            AmenityNotes = "Dune prism terrace, mineral-safe concierge core, and warp-side arcology docking spine.",
                            AtmosphereProfile = "Variable blend filters",
                            CreatedUtc = new DateTime(2026, 1, 12, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Earthlike pull",
                            HasBioluminescentSpa = false,
                            HasOxygen = true,
                            HasQuantumDock = true,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 533.00m,
                            PhotoUrl = "/images/seed-listings/glass-dune-arcology.png",
                            Summary = "A crystalline desert suite inside a megadome where mineral architecture glows at golden dusk.",
                            SupportsSiliconLifeforms = true,
                            VesselName = "The Glass Dune Arcology"
                        },
                        new
                        {
                            Id = 1009,
                            AlienLocation = "Frost Halo of Ilya Station",
                            AllowsAlienPets = false,
                            AmenityNotes = "Aurora bath chamber, thermal cocoon bedding, and glacier-lit reading pod.",
                            AtmosphereProfile = "Oxygen-rich",
                            CreatedUtc = new DateTime(2026, 1, 13, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Earthlike pull",
                            HasBioluminescentSpa = true,
                            HasOxygen = true,
                            HasQuantumDock = false,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 457.00m,
                            PhotoUrl = "/images/seed-listings/polar-aurora-refuge.png",
                            Summary = "An icy observatory refuge with aurora windows, heat-woven textiles, and restorative wellness alcoves.",
                            SupportsSiliconLifeforms = false,
                            VesselName = "The Polar Aurora Refuge"
                        },
                        new
                        {
                            Id = 1010,
                            AlienLocation = "Living Reef of Thalassa Gate",
                            AllowsAlienPets = true,
                            AmenityNotes = "Coral bloom canopy, companion tide pool, and reef-charged ambient wellness chamber.",
                            AtmosphereProfile = "Oxygen-rich",
                            CreatedUtc = new DateTime(2026, 1, 14, 18, 0, 0, 0, DateTimeKind.Utc),
                            GravityProfile = "Earthlike pull",
                            HasBioluminescentSpa = true,
                            HasOxygen = true,
                            HasQuantumDock = false,
                            HostUserId = "starstay-seed-host-curator",
                            NightlyRate = 578.00m,
                            PhotoUrl = "/images/seed-listings/coral-sun-atrium.png",
                            Summary = "A warm coral-vessel suite grown into a living reef canopy with golden tide light and bioengineered comfort.",
                            SupportsSiliconLifeforms = false,
                            VesselName = "The Coral Sun Atrium"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Xeno.Starstay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Xeno.Starstay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Xeno.Starstay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Xeno.Starstay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Xeno.Starstay.Models.StarshipBooking", b =>
                {
                    b.HasOne("Xeno.Starstay.Models.ApplicationUser", "GuestUser")
                        .WithMany("VoyagerBookings")
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Xeno.Starstay.Models.StarshipListing", "StarshipListing")
                        .WithMany("Bookings")
                        .HasForeignKey("StarshipListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestUser");

                    b.Navigation("StarshipListing");
                });

            modelBuilder.Entity("Xeno.Starstay.Models.StarshipListing", b =>
                {
                    b.HasOne("Xeno.Starstay.Models.ApplicationUser", "HostUser")
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("Xeno.Starstay.Models.ApplicationUser", b =>
                {
                    b.Navigation("VoyagerBookings");
                });

            modelBuilder.Entity("Xeno.Starstay.Models.StarshipListing", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
